const defaultEmployee = {
    persistenceId: undefined,
    phone: "",
    username: "",
    firstName: "",
    lastName: "",
    engine_id: "",
    status: "",
    email: "",
    workplaceId: "",
    positionName: "",
    contractTypeId: "",
    workTypeId: "",
    probationStartDate: "",
    probationEndDate: "",
    hrManagerAcceptance: "",
    hrManagerComment: "",
    directManagerComment: "",
    isActive: "",
    employeeTypeId: "",
    directManager_persistenceId: "",
    createdBy: "",
    createdDate: "",
    dateOfBirth: ""
};
export default defaultEmployee;