import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Analytics} from "@/components/analytics";
import {ThemeProvider} from "@/components/theme-provider";
import {Toaster} from "@/components/ui/toaster"
import StyledComponentsRegistry from "@/lib/AntdRegistry";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            <Toaster/>
        </ThemeProvider>
        <Analytics/>
        </body>
        </html>
    )
}
