import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Analytics} from "@/components/analytics";
import {ThemeProvider} from "@/components/theme-provider";
import {Toaster} from "@/components/ui/sonner"
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import {NextUIProviders} from "@/app/nextui-providers";

const nextFont = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Keistar',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={nextFont.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <NextUIProviders>
                <StyledComponentsRegistry>
                    {children}
                </StyledComponentsRegistry>
            </NextUIProviders>
            <Toaster/>
        </ThemeProvider>
        <Analytics/>
        </body>
        </html>
    )
}
